/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as _00StakingSol from "./00_Staking.sol";
export type { _00StakingSol };
import type * as _01VestingSol from "./01_Vesting.sol";
export type { _01VestingSol };
import type * as _02Erc20Sol from "./02_ERC20.sol";
export type { _02Erc20Sol };
export * as factories from "./factories";
export type { TokenStaking } from "./00_Staking.sol/TokenStaking";
export { TokenStaking__factory } from "./factories/00_Staking.sol/TokenStaking__factory";
export type { Vesting } from "./01_Vesting.sol/Vesting";
export { Vesting__factory } from "./factories/01_Vesting.sol/Vesting__factory";
export type { ERC20 } from "./02_ERC20.sol/ERC20";
export { ERC20__factory } from "./factories/02_ERC20.sol/ERC20__factory";
